// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gejystazkrkhjixrdguy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlanlzdGF6a3JraGppeHJkZ3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTI4MzcsImV4cCI6MjA3NDYyODgzN30.GDHIrSXUIE_cqyHIAErW6MsiHNAWcB6Xpnela8dKEWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});